### ISSUE TITLE
IDEA 2022.1 on v0.13.0 gradle fails to build project

### ISSUE THREAD

**Issue by houkunlin** [flikas/archived-idea-spring-boot-assistant#11]
```
Key in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionService duplicated; 
existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionService', serviceImplementation='in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=Spring Boot Assistant, id=dev.flikas.idea.spring.boot.assistant.plugin, descriptorPath=plugin.xml, path=D:\Program Files\JetBrains\Toolbox\apps\IDEA-U\ch-0\221.5080.210.plugins\idea-spring-boot-assistant, version=0.13.0, package=null, isBundled=false)); 
descriptor: in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl; app: Application (containerState=PRE_INIT) ; current plugin: dev.eltonsandre.intellij.spring.assistant.plugin

```

**Comment by flikas** [comment]
This because you've installed another [plugin](https://plugins.jetbrains.com/plugin/18622-spring-initializr-and-assistant)，these two plugins are forked from the same [origin](https://github.com/1tontech/intellij-spring-assistant)，has similar features, you can use any of them, but not both at the same time.
My advice, if you only need code completion in spring boot YAML configuration files, this one should be better. If you need Spring Initializer support or Properties configuration files support, use this [plugin](https://plugins.jetbrains.com/plugin/18622-spring-initializr-and-assistant) from [eltonsandre](https://plugins.jetbrains.com/organizations/eltonsandre)

**Comment by flikas** [comment]
Eltonsandre has fixed this problem, this issue can be closed.
